--EX 1:
select NAME from CITY where COUNTRYCODE = 'USA' AND POPULATION > 120000;
--EX 2:
select * from city where countrycode = 'JPN';
--EX 3:
select city, state from STATION WHERE LAT_N <> 0 AND LONG_W <> 0;
--EX 4:
SELECT CITY FROM STATION WHERE (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%') AND LAT_N <> 0 AND LONG_W <>0; 
--EX 5:
SELECT DISTINCT(CITY) FROM STATION WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u';
--EX 6:
SELECT DISTINCT(CITY) FROM STATION WHERE NOT (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%');
--EX 7:
SELECT NAME FROM EMPLOYEE ORDER BY NAME;
--EX 8:
SELECT NAME FROM EMPLOYEE WHERE SALARY >2000 AND MONTHS <10 ORDER BY EMPLOYEE_ID ASC;
--EX9:
SELECT PRODUCT_ID FROM PRODUCTS WHERE LOW_FATS = 'Y' AND RECYCLABLE = 'Y';
--EX10:
SELECT NAME FROM CUSTOMER WHERE REFEREE_ID <>2 OR REFEREE_ID IS NULL;
--EX 11:
SELECT NAME, POPULATION, AREA FROM WORLD WHERE AREA >= 3000000 OR POPULATION >= 25000000;
--EX 12:
SELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS WHERE AUTHOR_ID = VIEWER_ID ORDER BY AUTHOR_ID;
--EX 13;
SELECT PART, ASSEMBLY_STEP FROM PARTS_ASSEMBLY WHERE FINISH_DATE IS NULL;
--EX 14:
select * from lyft_drivers WHERE YEARLY_SALARY <= 30000 OR YEARLY_SALARY >= 70000;
--EX 15:
select advertising_channel from uber_advertising WHERE year = '2019' AND money_spent > 100000;
